restart_file: .na
start_datetime: 2022-09-12 00:00:00
end_datetime: .na
forecast_start_datetime: 2022-10-12 00:00:00
forecast_horizon: 0.0
sim_name: default
configure_flare: configure_flare.yml
configure_obs: observation_processing.yml
use_s3: no
